let list = [
  {
    alpha: "A",
    subItems: [
      { name: "阿坝藏族羌族自治州" },
      { name: "阿克苏地区" },
      { name: "阿拉尔市" },
      { name: "阿拉善盟" },
      { name: "阿勒泰地区" },
      { name: "阿里地区" },
      { name: "安康市" },
      { name: "安庆市" },
      { name: "鞍山市" },
      { name: "安顺市" },
      { name: "安阳市" },
      { name: "澳门半岛" },
    ],
  },
  {
    alpha: "B",
    subItems: [
      { name: "白城市" },
      { name: "百色市" },
      { name: "白沙黎族自治县" },
      { name: "白山市" },
      { name: "白银市" },
      { name: "巴南区" },
      { name: "宝坻区" },
      { name: "保定市" },
      { name: "宝鸡市" },
      { name: "宝山区" },
      { name: "保山市" },
      { name: "保亭黎族苗族自治县" },
      { name: "包头市" },
      { name: "巴彦淖尔市" },
      { name: "巴中市" },
      { name: "巴音郭楞蒙古自治州" },
      { name: "北碚区" },
      { name: "北辰区" },
      { name: "北海市" },
      { name: "北区" },
      { name: "北屯市" },
      { name: "蚌埠市" },
      { name: "本溪市" },
      { name: "毕节市" },
      { name: "滨海新区" },
      { name: "滨州市" },
      { name: "璧山区" },
      { name: "亳州市" },
      { name: "博尔塔拉蒙古自治州" },
    ],
  },
  {
    alpha: "C",
    subItems: [
      { name: "沧州市" },
      { name: "长春市" },
      { name: "常德市" },
      { name: "昌都市" },
      { name: "昌吉回族自治州" },
      { name: "昌江黎族自治县" },
      { name: "长宁区" },
      { name: "昌平区" },
      { name: "长沙市" },
      { name: "长寿区" },
      { name: "长治市" },
      { name: "常州市" },
      { name: "朝阳区" },
      { name: "朝阳市" },
      { name: "潮州市" },
      { name: "承德市" },
      { name: "成都市" },
      { name: "城口县" },
      { name: "澄迈县" },
      { name: "郴州市" },
      { name: "赤峰市" },
      { name: "池州市" },
      { name: "崇明区" },
      { name: "崇左市" },
      { name: "楚雄彝族自治州" },
      { name: "滁州市" },
    ],
  },
  {
    alpha: "D",
    subItems: [
      { name: "大渡口区" },
      { name: "大理白族自治州" },
      { name: "大连市" },
      { name: "丹东市" },
      { name: "凼仔" },
      { name: "儋州市" },
      { name: "大埔区" },
      { name: "大庆市" },
      { name: "大同市" },
      { name: "大兴区" },
      { name: "大兴安岭地区" },
      { name: "达州市" },
      { name: "大足区" },
      { name: "德宏傣族景颇族自治州" },
      { name: "德阳市" },
      { name: "德州市" },
      { name: "垫江县" },
      { name: "定安县" },
      { name: "定西市" },
      { name: "迪庆藏族自治州" },
      { name: "东城区" },
      { name: "东方市" },
      { name: "东莞市" },
      { name: "东丽区" },
      { name: "东区" },
      { name: "东营市" },
    ],
  },
  {
    alpha: "E",
    subItems: [
      { name: "鄂尔多斯市" },
      { name: "恩施土家族苗族自治州" },
      { name: "鄂州市" },
    ],
  },
  {
    alpha: "F",
    subItems: [
      { name: "防城港市" },
      { name: "房山区" },
      { name: "丰都县" },
      { name: "奉节县" },
      { name: "丰台区" },
      { name: "奉贤区" },
      { name: "佛山市" },
      { name: "涪陵区" },
      { name: "抚顺市" },
      { name: "阜新市" },
      { name: "阜阳市" },
      { name: "福州市" },
      { name: "抚州市" },
    ],
  },
  {
    alpha: "G",
    subItems: [
      { name: "甘南藏族自治州" },
      { name: "赣州市" },
      { name: "甘孜藏族自治州" },
      { name: "高雄市" },
      { name: "广安市" },
      { name: "广元市" },
      { name: "广州市" },
      { name: "观塘区" },
      { name: "贵港市" },
      { name: "桂林市" },
      { name: "贵阳市" },
      { name: "果洛藏族自治州" },
      { name: "固原市" },
    ],
  },
  {
    alpha: "H",
    subItems: [
      { name: "哈尔滨市" },
      { name: "海北藏族自治州" },
      { name: "海淀区" },
      { name: "海东市" },
      { name: "海口市" },
      { name: "海南藏族自治州" },
      { name: "海西蒙古族藏族自治州" },
      { name: "哈密市" },
      { name: "邯郸市" },
      { name: "杭州市" },
      { name: "汉中市" },
      { name: "河北区" },
      { name: "鹤壁市" },
      { name: "河池市" },
      { name: "合川区" },
      { name: "河东区" },
      { name: "合肥市" },
      { name: "鹤岗市" },
      { name: "黑河市" },
      { name: "衡水市" },
      { name: "衡阳市" },
      { name: "和平区" },
      { name: "和田地区" },
      { name: "河西区" },
      { name: "河源市" },
      { name: "菏泽市" },
      { name: "贺州市" },
      { name: "红河哈尼族彝族自治州" },
      { name: "虹口区" },
      { name: "红桥区" },
      { name: "淮安市" },
      { name: "淮北市" },
      { name: "怀化市" },
      { name: "淮南市" },
      { name: "怀柔区" },
      { name: "花莲县" },
      { name: "黄大仙区" },
      { name: "黄冈市" },
      { name: "黄南藏族自治州" },
      { name: "黄浦区" },
      { name: "黄山市" },
      { name: "黄石市" },
      { name: "呼和浩特市" },
      { name: "惠州市" },
      { name: "葫芦岛市" },
      { name: "呼伦贝尔市" },
      { name: "湖州市" },
    ],
  },
  {
    alpha: "J",
    subItems: [
      { name: "嘉定区" },
      { name: "佳木斯市" },
      { name: "吉安市" },
      { name: "江北区" },
      { name: "江津区" },
      { name: "江门市" },
      { name: "焦作市" },
      { name: "嘉兴市" },
      { name: "嘉义市" },
      { name: "嘉义县" },
      { name: "嘉峪关市" },
      { name: "揭阳市" },
      { name: "吉林市" },
      { name: "基隆市" },
      { name: "济南市" },
      { name: "金昌市" },
      { name: "晋城市" },
      { name: "静安区" },
      { name: "景德镇市" },
      { name: "静海区" },
      { name: "荆门市" },
      { name: "荆州市" },
      { name: "金华市" },
      { name: "济宁市" },
      { name: "津南区" },
      { name: "金山区" },
      { name: "晋中市" },
      { name: "锦州市" },
      { name: "九江市" },
      { name: "九龙城区" },
      { name: "九龙坡区" },
      { name: "酒泉市" },
      { name: "鸡西市" },
      { name: "济源市" },
      { name: "蓟州区" },
    ],
  },
  {
    alpha: "K",
    subItems: [
      { name: "开封市" },
      { name: "开州区" },
      { name: "喀什地区" },
      { name: "可克达拉市" },
      { name: "克拉玛依市" },
      { name: "克孜勒苏柯尔克孜自治州" },
      { name: "葵青区" },
      { name: "昆明市" },
      { name: "昆玉市" },
    ],
  },
  {
    alpha: "L",
    subItems: [
      { name: "来宾市" },
      { name: "廊坊市" },
      { name: "兰州市" },
      { name: "拉萨市" },
      { name: "乐东黎族自治县" },
      { name: "乐山市" },
      { name: "梁平区" },
      { name: "凉山彝族自治州" },
      { name: "连云港市" },
      { name: "聊城市" },
      { name: "辽阳市" },
      { name: "辽源市" },
      { name: "离岛区" },
      { name: "丽江市" },
      { name: "临沧市" },
      { name: "临汾市" },
      { name: "临高县" },
      { name: "陵水黎族自治县" },
      { name: "临夏回族自治州" },
      { name: "临沂市" },
      { name: "林芝市" },
      { name: "丽水市" },
      { name: "六安市" },
      { name: "六盘水市" },
      { name: "柳州市" },
      { name: "陇南市" },
      { name: "龙岩市" },
      { name: "娄底市" },
      { name: "路凼城" },
      { name: "路环" },
      { name: "漯河市" },
      { name: "洛阳市" },
      { name: "泸州市" },
      { name: "吕梁市" },
    ],
  },
  {
    alpha: "M",
    subItems: [
      { name: "马鞍山市" },
      { name: "茂名市" },
      { name: "眉山市" },
      { name: "梅州市" },
      { name: "门头沟区" },
      { name: "绵阳市" },
      { name: "苗栗县" },
      { name: "闵行区" },
      { name: "密云区" },
      { name: "牡丹江市" },
    ],
  },
  {
    alpha: "N",
    subItems: [
      { name: "南岸区" },
      { name: "南昌市" },
      { name: "南充市" },
      { name: "南川区" },
      { name: "南京市" },
      { name: "南开区" },
      { name: "南宁市" },
      { name: "南平市" },
      { name: "南区" },
      { name: "南通市" },
      { name: "南投县" },
      { name: "南阳市" },
      { name: "那曲市" },
      { name: "内江市" },
      { name: "宁波市" },
      { name: "宁德市" },
      { name: "宁河区" },
      { name: "怒江傈僳族自治州" },
    ],
  },
  {
    alpha: "P",
    subItems: [
      { name: "盘锦市" },
      { name: "攀枝花市" },
      { name: "澎湖县" },
      { name: "彭水苗族土家族自治县" },
      { name: "平顶山市" },
      { name: "屏东县" },
      { name: "平谷区" },
      { name: "平凉市" },
      { name: "萍乡市" },
      { name: "浦东新区" },
      { name: "普洱市" },
      { name: "莆田市" },
      { name: "普陀区" },
      { name: "濮阳市" },
    ],
  },
  {
    alpha: "Q",
    subItems: [
      { name: "黔东南苗族侗族自治州" },
      { name: "潜江市" },
      { name: "黔江区" },
      { name: "黔南布依族苗族自治州" },
      { name: "黔西南布依族苗族自治州" },
      { name: "綦江区" },
      { name: "青岛市" },
      { name: "青浦区" },
      { name: "庆阳市" },
      { name: "清远市" },
      { name: "秦皇岛市" },
      { name: "钦州市" },
      { name: "琼海市" },
      { name: "琼中黎族苗族自治县" },
      { name: "齐齐哈尔市" },
      { name: "七台河市" },
      { name: "荃湾区" },
      { name: "泉州市" },
      { name: "曲靖市" },
      { name: "衢州市" },
    ],
  },
  {
    alpha: "R",
    subItems: [{ name: "日喀则市" }, { name: "日照市" }, { name: "荣昌区" }],
  },
  {
    alpha: "S",
    subItems: [
      { name: "三门峡市" },
      { name: "三明市" },
      { name: "三沙市" },
      { name: "三亚市" },
      { name: "商洛市" },
      { name: "商丘市" },
      { name: "上饶市" },
      { name: "山南市" },
      { name: "汕头市" },
      { name: "汕尾市" },
      { name: "韶关市" },
      { name: "绍兴市" },
      { name: "邵阳市" },
      { name: "沙坪坝区" },
      { name: "沙田区" },
      { name: "神农架林区" },
      { name: "深水埗区" },
      { name: "沈阳市" },
      { name: "深圳市" },
      { name: "石河子市" },
      { name: "石家庄市" },
      { name: "石景山区" },
      { name: "十堰市" },
      { name: "石柱土家族自治县" },
      { name: "石嘴山市" },
      { name: "双河市" },
      { name: "双鸭山市" },
      { name: "顺义区" },
      { name: "朔州市" },
      { name: "四平市" },
      { name: "松江区" },
      { name: "松原市" },
      { name: "绥化市" },
      { name: "遂宁市" },
      { name: "随州市" },
      { name: "宿迁市" },
      { name: "苏州市" },
      { name: "宿州市" },
    ],
  },
  {
    alpha: "T",
    subItems: [
      { name: "塔城地区" },
      { name: "泰安市" },
      { name: "台北市" },
      { name: "台东县" },
      { name: "台南市" },
      { name: "太原市" },
      { name: "台中市" },
      { name: "泰州市" },
      { name: "台州市" },
      { name: "唐山市" },
      { name: "桃园市" },
      { name: "天门市" },
      { name: "天水市" },
      { name: "铁岭市" },
      { name: "铁门关市" },
      { name: "铜川市" },
      { name: "通化市" },
      { name: "铜梁区" },
      { name: "通辽市" },
      { name: "铜陵市" },
      { name: "潼南区" },
      { name: "铜仁市" },
      { name: "通州区" },
      { name: "吐鲁番市" },
      { name: "图木舒克市" },
      { name: "屯昌县" },
      { name: "屯门区" },
    ],
  },
  {
    alpha: "W",
    subItems: [
      { name: "万宁市" },
      { name: "万州区" },
      { name: "湾仔区" },
      { name: "潍坊市" },
      { name: "威海市" },
      { name: "渭南市" },
      { name: "文昌市" },
      { name: "文山壮族苗族自治州" },
      { name: "温州市" },
      { name: "乌海市" },
      { name: "武汉市" },
      { name: "芜湖市" },
      { name: "五家渠市" },
      { name: "乌兰察布市" },
      { name: "武隆区" },
      { name: "乌鲁木齐市" },
      { name: "武清区" },
      { name: "巫山县" },
      { name: "武威市" },
      { name: "无锡市" },
      { name: "巫溪县" },
      { name: "五指山市" },
      { name: "吴忠市" },
      { name: "梧州市" },
    ],
  },
  {
    alpha: "X",
    subItems: [
      { name: "厦门市" },
      { name: "西安市" },
      { name: "湘潭市" },
      { name: "湘西土家族苗族自治州" },
      { name: "襄阳市" },
      { name: "咸宁市" },
      { name: "仙桃市" },
      { name: "咸阳市" },
      { name: "孝感市" },
      { name: "西城区" },
      { name: "西贡区" },
      { name: "锡林郭勒盟" },
      { name: "新北市" },
      { name: "兴安盟" },
      { name: "邢台市" },
      { name: "西宁市" },
      { name: "新乡市" },
      { name: "信阳市" },
      { name: "新余市" },
      { name: "忻州市" },
      { name: "新竹市" },
      { name: "新竹县" },
      { name: "西青区" },
      { name: "西双版纳傣族自治州" },
      { name: "秀山土家族苗族自治县" },
      { name: "宣城市" },
      { name: "许昌市" },
      { name: "徐汇区" },
      { name: "徐州市" },
    ],
  },
  {
    alpha: "Y",
    subItems: [
      { name: "雅安市" },
      { name: "延安市" },
      { name: "延边朝鲜族自治州" },
      { name: "盐城市" },
      { name: "阳江市" },
      { name: "杨浦区" },
      { name: "阳泉市" },
      { name: "扬州市" },
      { name: "延庆区" },
      { name: "烟台市" },
      { name: "宜宾市" },
      { name: "宜昌市" },
      { name: "伊春市" },
      { name: "宜春市" },
      { name: "宜兰县" },
      { name: "伊犁哈萨克自治州" },
      { name: "银川市" },
      { name: "营口市" },
      { name: "鹰潭市" },
      { name: "益阳市" },
      { name: "永川区" },
      { name: "永州市" },
      { name: "油尖旺区" },
      { name: "酉阳土家族苗族自治县" },
      { name: "元朗区" },
      { name: "渝北区" },
      { name: "岳阳市" },
      { name: "玉林市" },
      { name: "榆林市" },
      { name: "运城市" },
      { name: "云浮市" },
      { name: "云林县" },
      { name: "云阳县" },
      { name: "玉树藏族自治州" },
      { name: "玉溪市" },
      { name: "渝中区" },
    ],
  },
  {
    alpha: "Z",
    subItems: [
      { name: "枣庄市" },
      { name: "彰化县" },
      { name: "张家界市" },
      { name: "张家口市" },
      { name: "张掖市" },
      { name: "漳州市" },
      { name: "湛江市" },
      { name: "肇庆市" },
      { name: "昭通市" },
      { name: "郑州市" },
      { name: "镇江市" },
      { name: "中山市" },
      { name: "中卫市" },
      { name: "忠县" },
      { name: "中西区" },
      { name: "周口市" },
      { name: "舟山市" },
      { name: "珠海市" },
      { name: "驻马店市" },
      { name: "株洲市" },
      { name: "淄博市" },
      { name: "自贡市" },
      { name: "资阳市" },
      { name: "遵义市" },
    ],
  },
];

let list2 = [
  {
    alpha: "B",
    subItems: [
      {
        fid: "288",
        name: "板栗",
      },
      {
        fid: "452",
        name: "棒菜",
      },
      {
        fid: "438",
        name: "包菜",
      },
      {
        fid: "420",
        name: "贝类",
      },
      {
        fid: "218",
        name: "扁豆",
      },
      {
        fid: "439",
        name: "鳖",
      },
      {
        fid: "301",
        name: "槟榔",
      },
      {
        fid: "227",
        name: "菠菜",
      },
      {
        fid: "297",
        name: "菠萝",
      },
    ],
  },
  {
    alpha: "C",
    subItems: [
      {
        fid: "217",
        name: "菜豆",
      },
      {
        fid: "213",
        name: "菜用大豆",
      },
      {
        fid: "448",
        name: "菜竹",
      },
      {
        fid: "216",
        name: "蚕豆",
      },
      {
        fid: "332",
        name: "草类药材及叶用药材",
      },
      {
        fid: "311",
        name: "草莓",
      },
      {
        fid: "449",
        name: "草莓苗",
      },
      {
        fid: "326",
        name: "茶叶",
      },
      {
        fid: "295",
        name: "橙",
      },
      {
        fid: "251",
        name: "慈菇",
      },
      {
        fid: "241",
        name: "葱",
      },
    ],
  },
  {
    alpha: "D",
    subItems: [
      {
        fid: "212",
        name: "大白菜",
      },
      {
        fid: "239",
        name: "大葱",
      },
      {
        fid: "322",
        name: "大豆",
      },
      {
        fid: "336",
        name: "大麦",
      },
      {
        fid: "238",
        name: "大蒜",
      },
      {
        fid: "426",
        name: "淡溪白对虾",
      },
      {
        fid: "430",
        name: "蛋鸡",
      },
      {
        fid: "222",
        name: "冬瓜",
      },
      {
        fid: "442",
        name: "冬枣",
      },
    ],
  },
  {
    alpha: "E",
    subItems: [
      {
        fid: "437",
        name: "儿菜",
      },
    ],
  },
  {
    alpha: "F",
    subItems: [
      {
        fid: "253",
        name: "番茄",
      },
      {
        fid: "454",
        name: "覆盆子",
      },
    ],
  },
  {
    alpha: "G",
    subItems: [
      {
        fid: "211",
        name: "甘蓝",
      },
      {
        fid: "243",
        name: "甘薯",
      },
      {
        fid: "325",
        name: "甘蔗",
      },
      {
        fid: "293",
        name: "柑橘",
      },
      {
        fid: "286",
        name: "橄榄",
      },
      {
        fid: "341",
        name: "高粱",
      },
      {
        fid: "275",
        name: "枸杞",
      },
      {
        fid: "425",
        name: "瓜子蛤",
      },
      {
        fid: "215",
        name: "豇豆",
      },
    ],
  },
  {
    alpha: "H",
    subItems: [
      {
        fid: "315",
        name: "哈密瓜",
      },
      {
        fid: "418",
        name: "海带",
      },
      {
        fid: "421",
        name: "海水贝类",
      },
      {
        fid: "398",
        name: "杭白菊",
      },
      {
        fid: "287",
        name: "核桃",
      },
      {
        fid: "444",
        name: "红美人",
      },
      {
        fid: "246",
        name: "胡萝卜",
      },
      {
        fid: "408",
        name: "胡柚",
      },
      {
        fid: "428",
        name: "湖羊",
      },
      {
        fid: "225",
        name: "瓠瓜",
      },
      {
        fid: "329",
        name: "花类药材",
      },
      {
        fid: "319",
        name: "花生",
      },
      {
        fid: "209",
        name: "花椰菜",
      },
      {
        fid: "220",
        name: "黄瓜",
      },
      {
        fid: "236",
        name: "黄花菜",
      },
      {
        fid: "400",
        name: "黄桃",
      },
      {
        fid: "232",
        name: "茴香",
      },
      {
        fid: "302",
        name: "火龙果",
      },
    ],
  },
  {
    alpha: "J",
    subItems: [
      {
        fid: "435",
        name: "鸡",
      },
      {
        fid: "410",
        name: "鸡毛菜",
      },
      {
        fid: "249",
        name: "茭白",
      },
      {
        fid: "237",
        name: "芥菜",
      },
      {
        fid: "234",
        name: "芥蓝",
      },
      {
        fid: "441",
        name: "金桔",
      },
      {
        fid: "228",
        name: "韭菜",
      },
    ],
  },
  {
    alpha: "K",
    subItems: [
      {
        fid: "327",
        name: "咖啡",
      },
      {
        fid: "230",
        name: "空心菜",
      },
      {
        fid: "223",
        name: "苦瓜",
      },
    ],
  },
  {
    alpha: "L",
    subItems: [
      {
        fid: "255",
        name: "辣椒",
      },
      {
        fid: "436",
        name: "蓝莓",
      },
      {
        fid: "453",
        name: "雷竹",
      },
      {
        fid: "266",
        name: "梨",
      },
      {
        fid: "279",
        name: "李",
      },
      {
        fid: "284",
        name: "荔枝",
      },
      {
        fid: "250",
        name: "莲藕",
      },
      {
        fid: "412",
        name: "莲蓬",
      },
      {
        fid: "402",
        name: "菱",
      },
      {
        fid: "283",
        name: "龙眼",
      },
      {
        fid: "257",
        name: "芦笋",
      },
      {
        fid: "247",
        name: "萝卜",
      },
      {
        fid: "233",
        name: "落葵",
      },
    ],
  },
  {
    alpha: "M",
    subItems: [
      {
        fid: "317",
        name: "麻类",
      },
      {
        fid: "242",
        name: "马铃薯",
      },
      {
        fid: "445",
        name: "麦冬",
      },
      {
        fid: "285",
        name: "芒果",
      },
      {
        fid: "446",
        name: "毛豆",
      },
      {
        fid: "280",
        name: "梅",
      },
      {
        fid: "271",
        name: "猕猴桃",
      },
      {
        fid: "431",
        name: "蜜蜂",
      },
      {
        fid: "399",
        name: "蜜梨",
      },
      {
        fid: "316",
        name: "棉花",
      },
      {
        fid: "447",
        name: "苗木",
      },
    ],
  },
  {
    alpha: "N",
    subItems: [
      {
        fid: "219",
        name: "南瓜",
      },
      {
        fid: "294",
        name: "柠檬",
      },
      {
        fid: "433",
        name: "牛",
      },
    ],
  },
  {
    alpha: "P",
    subItems: [
      {
        fid: "333",
        name: "皮类药材病害",
      },
      {
        fid: "268",
        name: "枇杷",
      },
      {
        fid: "265",
        name: "苹果",
      },
      {
        fid: "310",
        name: "葡萄",
      },
      {
        fid: "401",
        name: "蒲瓜",
      },
    ],
  },
  {
    alpha: "Q",
    subItems: [
      {
        fid: "338",
        name: "荞麦",
      },
      {
        fid: "254",
        name: "茄子",
      },
      {
        fid: "235",
        name: "芹菜",
      },
      {
        fid: "210",
        name: "青菜",
      },
      {
        fid: "413",
        name: "青瓜",
      },
      {
        fid: "423",
        name: "青蟹",
      },
      {
        fid: 195,
        name: "其他",
        subItemsing: "QT",
      },
    ],
  },
  {
    alpha: "R",
    subItems: [
      {
        fid: "274",
        name: "人参果",
      },
      {
        fid: "429",
        name: "肉鸡",
      },
    ],
  },
  {
    alpha: "S",
    subItems: [
      {
        fid: "318",
        name: "桑树",
      },
      {
        fid: "289",
        name: "山核桃",
      },
      {
        fid: "244",
        name: "山药",
      },
      {
        fid: "267",
        name: "山楂",
      },
      {
        fid: "226",
        name: "蛇瓜",
      },
      {
        fid: "229",
        name: "生菜",
      },
      {
        fid: "252",
        name: "生姜",
      },
      {
        fid: "272",
        name: "石榴",
      },
      {
        fid: "406",
        name: "食用菌",
      },
      {
        fid: "269",
        name: "柿子",
      },
      {
        fid: "342",
        name: "黍稷",
      },
      {
        fid: "335",
        name: "水稻",
      },
      {
        fid: "221",
        name: "丝瓜",
      },
      {
        fid: "409",
        name: "四季豆",
      },
      {
        fid: "343",
        name: "粟",
      },
      {
        fid: "248",
        name: "笋",
      },
    ],
  },
  {
    alpha: "T",
    subItems: [
      {
        fid: "278",
        name: "桃",
      },
      {
        fid: "450",
        name: "桃形李",
      },
      {
        fid: "324",
        name: "甜菜",
      },
      {
        fid: "313",
        name: "甜瓜",
      },
      {
        fid: "407",
        name: "甜椒",
      },
      {
        fid: "403",
        name: "甜油菜",
      },
      {
        fid: "258",
        name: "甜玉米",
      },
      {
        fid: "231",
        name: "茼蒿",
      },
    ],
  },
  {
    alpha: "W",
    subItems: [
      {
        fid: "214",
        name: "豌豆",
      },
      {
        fid: "256",
        name: "莴笋",
      },
      {
        fid: "300",
        name: "无花果",
      },
    ],
  },
  {
    alpha: "X",
    subItems: [
      {
        fid: "273",
        name: "西番莲",
      },
      {
        fid: "312",
        name: "西瓜",
      },
      {
        fid: "224",
        name: "西葫芦瓜",
      },
      {
        fid: "397",
        name: "西兰花",
      },
      {
        fid: "427",
        name: "虾",
      },
      {
        fid: "394",
        name: "苋菜",
      },
      {
        fid: "291",
        name: "香榧",
      },
      {
        fid: "314",
        name: "香瓜",
      },
      {
        fid: "270",
        name: "香蕉",
      },
      {
        fid: "323",
        name: "向日葵",
      },
      {
        fid: "440",
        name: "小番茄",
      },
      {
        fid: "411",
        name: "小茭菜",
      },
      {
        fid: "337",
        name: "小麦",
      },
      {
        fid: "424",
        name: "蟹",
      },
      {
        fid: "281",
        name: "杏",
      },
    ],
  },
  {
    alpha: "Y",
    subItems: [
      {
        fid: "434",
        name: "鸭",
      },
      {
        fid: "328",
        name: "烟叶",
      },
      {
        fid: "339",
        name: "燕麦",
      },
      {
        fid: "417",
        name: "羊歇菜",
      },
      {
        fid: "277",
        name: "杨梅",
      },
      {
        fid: "299",
        name: "杨桃",
      },
      {
        fid: "240",
        name: "洋葱",
      },
      {
        fid: "172",
        name: "药材",
      },
      {
        fid: "298",
        name: "椰子",
      },
      {
        fid: "290",
        name: "银杏",
      },
      {
        fid: "276",
        name: "樱桃",
      },
      {
        fid: "443",
        name: "由良",
      },
      {
        fid: "320",
        name: "油菜",
      },
      {
        fid: "392",
        name: "油麦菜",
      },
      {
        fid: "296",
        name: "柚",
      },
      {
        fid: "422",
        name: "鱼",
      },
      {
        fid: "340",
        name: "玉米",
      },
      {
        fid: "245",
        name: "芋",
      },
    ],
  },
  {
    alpha: "Z",
    subItems: [
      {
        fid: "282",
        name: "枣",
      },
      {
        fid: "292",
        name: "榛",
      },
      {
        fid: "321",
        name: "芝麻",
      },
      {
        fid: "331",
        name: "种子果实类药材",
      },
      {
        fid: "432",
        name: "猪",
      },
      {
        fid: "419",
        name: "紫菜",
      },
    ],
  },
];

export default list2;
